---
- name: make sure deploy dir exists
  file:
    path: "{{ findit_app_dir }}"
    owner: "{{ deploy_user }}"
    state: directory
    recurse: true
  become: true

- name: get application from repo
  git:
    repo: "{{ findit_app_repo }}"
    dest: "{{ findit_app_dir }}"
    version: "{{ findit_app_branch | default('HEAD') }}"
    key_file: "{{ deploy_key_full_path }}"
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: "Install Bundler"
  gem:
    name: bundler 
    state: latest
  notify: restart apache
  become_user: "{{ findit_app_user }}"
