---
- name: install epel repo
  become: yes
  yum: name=epel-release state=present

- name: install prereqs - RedHat
  become: yes
  yum: 
    state: present
    name: 
      - nodejs
      - git
      - policycoreutils-python
      - libselinux-python
      - gcc
      - sqlite-devel
      - mariadb-devel
      - gcc-c++
      - libstdc++-devel
      - libxslt-devel
      - libxml2-devel
