---
- name: install epel repo
  become: true
  yum: name=epel-release state=present

- name: install prereqs - RedHat
  become: true
  yum: name={{ item }} state=present
  with_items:
    - nodejs
    - git
    - policycoreutils-python
    - libselinux-python
    - gcc
    - sqlite-devel
    - mariadb-devel
    - gcc-c++
    - libstdc++-devel
    - libxslt-devel
    - libxml2-devel
